title: 游方艾
email: your-email@example.com
description: "思考的艺术"
baseurl: ""  
url: "https://blog.ufindai.com"  
github_username: pcliu

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin : "dirt"

locale: "zh-CN"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-mermaid

permalink: /:categories/:title/

# Pagination with jekyll-paginate
paginate: 10 # amount of posts to show
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

sidebar:
  nav: "docs" 
  
search : true
search_full_content : true
search_provider : lunr
lunr:
  search_within_pages    : true

logo: "/assets/images/sailboat_logo_enlarged_88x88.png"

mathjax: true

sass:
  sass_dir: _sass
  style: compressed

analytics:
  provider: "google-gtag"  # 使用最新的 gtag.js
  google:
    tracking_id: "G-V0092YMJ2R"  # 你的 GA4 跟踪 ID
    anonymize_ip: false  # 可选,是否匿名化 IP

repository: "pcliu/blog"  # 例如: "username/username.github.io"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDONH3Uvg"
    category_name        : "General"
    category_id          : "DIC_kwDONH3Uvs4CkZLi"
    discussion_term      : "pathname"
    reactions_enabled    : '1'
    theme               : "light"

# Mermaid 配置
mermaid:
  # 启用 mermaid
  enabled: true
  # 版本号,建议使用最新稳定版
  version: "11.4.0" 
  # 主题配置
  theme: "default"
