title: 游方埃
email: your-email@example.com
description: >- 
  Your blog description
baseurl: ""  # 因为你的仓库名是 blog
url: "https://blog.ufindai.com"  # 你的 GitHub Pages URL
github_username: pcliu

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin : "contrast"

locale: "zh-CN"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

permalink: /:categories/:title/

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

sidebar:
  nav: "docs" 




