title: 技术日记
email: your-email@example.com
description: >- 
  Your blog description
baseurl: "/blog"  # 因为你的仓库名是 blog
url: "https://pcliu.github.io"  # 你的 GitHub Pages URL
github_username: pcliu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
