title: 游方艾
email: your-email@example.com
description: "思考的艺术"
baseurl: ""  
url: "https://blog.ufindai.com"  
github_username: pcliu

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin : "dirt"

locale: "zh-CN"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

permalink: /:categories/:title/

# Pagination with jekyll-paginate
paginate: 10 # amount of posts to show
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

sidebar:
  nav: "docs" 
  
search : true
search_full_content : true
search_provider : lunr
lunr:
  search_within_pages    : true

logo: "/assets/images/sailboat_logo_enlarged_88x88.png"

mathjax: true

sass:
  sass_dir: _sass
  style: compressed


