title: 技术日记
email: your-email@example.com
description: >- 
  Your blog description
baseurl: "/blog"  # 因为你的仓库名是 blog
url: "https://pcliu.github.io"  # 你的 GitHub Pages URL
github_username: pcliu

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

locale: "zh-CN"

sidebar:
  nav: "docs" 

defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

# 分页配置
paginate: 5

# 主题皮肤
minimal_mistakes_skin: "dirt"
